### DISCUSSION TITLE
Chart Rendering Issue on 2.9.4 version

### DISCUSSION THREAD

**Discussion by Teviwe** [kedacore/charts#507] [Q&A]
Good day.

We have encountered an issue with incorrect rendering of values for additionalAnnotations in chart version 2.9.4:
```yaml
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0    app: keda
  labels:
```
After looking at the issues, I noticed that similar problems were experienced by others as well:
https://github.com/kedacore/charts/issues/437

Furthermore, there were fixes made for this:
https://github.com/kedacore/charts/pull/353
https://github.com/kedacore/charts/pull/482

Could you please backport these changes to the older Helm charts?
At least for version 2.9.4, which is relevant for Kubernetes 1.23.

This would prevent us from forking your charts and allow us to use the updated fixes.

Thank you in advance.
