### ISSUE TITLE
Chart expects Helm 3 / apiVersion: v2, but is published as 2/v1

### ISSUE THREAD

**Issue by jyaworski** [kedacore/charts#110]
Hello:

At https://kedacore.github.io/charts/index.yaml, the chart version `2.0.0` is published as `apiVersion: v1`:

```
keda:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-11-04T15:14:39.6686554+01:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: dba8b0e793085165c7d155f9393c5ff112d4714dbce0201404ceb0e67d1b2deb
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/master/images/keda-logo-500x500-white.png
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - https://kedacore.github.io/charts/keda-2.0.0.tgz
    version: 2.0.0
```

Could the chart be incremented and republished as `apiVersion: v2`? Thank you!
