### ISSUE TITLE
Getting error on helm update

### ISSUE THREAD

**Issue by arthuravila26** [kedacore/charts#138]
G'day everyone!

This is the first time ever that I'm deploying Keda manifests using a helm chart.
I'm trying to deploy my application to my AKS cluster. At the time Helm is doing the Upgrade I get this error:

`
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: ScaledObject "My-Chart-Name" in namespace "My-Namespace" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "My-Chart-Name"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "My-Namespace" 
`
Do I really need this labels? Because I don't use it in my deployment for example and It worked just fine, this problem just happen when I create a manifest for Keda.

My folder tree is like:

```
Chart-Folder
└── templates
    └── deployment.yml
    └── scaledobject.yml
└── Chart.yaml
└── values.yml
```

My scaledobject.yml is like:

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    deploymentName: {{ .Chart.Name }}
spec:
  scaleTargetRef:
    deploymentName: {{ .Chart.Name }}
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 1
  triggers:
  - type: azure-servicebus
    metadata:
      topicName: My-Topic
      subscriptionName: My-Subscription
      messageCount: '1'
      connection: AzureWebJobsStorage
```

My chart.yml:

```
apiVersion: v1
appVersion: "1.0"
description: My Description
name: My Chart name
version: 0.1.0
```

Does anyone has a clue of what I'm missing here?

Thanks!

**Comment by tomkerkhove** [comment]
It looks like that resource already exists in your cluster & namespace, did you create it before without Helm?

**Comment by zroubalik** [comment]
What KEDA version are you using? Seems like some 1.x. I definitely recommend to migrate to 2.x

**Comment by arthuravila26** [comment]
> It looks like that resource already exists in your cluster & namespace, did you create it before without Helm?

Yes, I did. But when I saw this error I removed the deployment and other manifests from that deployment and nothig changed.

**Comment by arthuravila26** [comment]
> What KEDA version are you using? Seems like some 1.x. I definitely recommend to migrate to 2.x

I'm actually using the version 2.x of Keda.

**Comment by zroubalik** [comment]
So please refer our migration guide https://deploy-preview-218--keda.netlify.app/docs/2.0/migration/

I can see that you are using old `apiVersion` and spec in the ScaledObject definition.

**Comment by arthuravila26** [comment]
> So please refer our migration guide https://deploy-preview-218--keda.netlify.app/docs/2.0/migration/
> 
> I can see that you are using old `apiVersion` and spec in the ScaledObject definition.

Well, just tried that and didn't work yet. I'm currently using keda version 2.1. My ScaledObject is looking like that now:
```
apiVersion: keda.sh/v1alpha1 
kind: ScaledObject
metadata:
  name: {{ .Chart.Name }}
spec:
  scaleTargetRef:
    name: {{ .Chart.Name }}
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 1
  triggers:
```
