### ISSUE TITLE
Improve the consistency in KEDA chart

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/charts#182]
Working with KEDA chart, I found that it hasn't got consistency in the names when it refers to each application, for example, sometimes the operator is named [`keda` ](https://github.com/kedacore/charts/blob/master/keda/values.yaml#L6) and other times is named [`operator`](https://github.com/kedacore/charts/blob/master/keda/values.yaml#L22). With metrics server happens the same, sometimes is called as [`metricsApiServer`](https://github.com/kedacore/charts/blob/master/keda/values.yaml#L10), or as [`metricsServer`](https://github.com/kedacore/charts/blob/master/keda/values.yaml#L25), or as [`metricsAdapter`](https://github.com/kedacore/charts/blob/master/keda/values.yaml#L33).

This is a breaking change, but maybe it could be in the next major release, and it reduces the complexity of the chart. IDK, maybe the chart values could be something like:
```yaml
operator:
  resources: {}
  tag: {}
  logging: {}
  # .....
metricsServer:
  resources: {}
  tag: {}
  logging: {}
```

IMHO, at least the naming should be unified to reduce the general complexity 
Wdyt?
