### ISSUE TITLE
Deploying a ScaledJob and ScaledObject fails

### ISSUE THREAD

**Issue by prak2419** [kedacore/charts#186]
The deployment of a ScaledJob and a ScaledDeployment worked until yesterday, but today it is failing with the following error,

```bash
error: unable to recognize ".\\scale_job.yml": no matches for kind "ScaledJob" in version "keda.sh/v1alpha1"
```
The installed version of kedacore is 2.4.0

```bash
helm ls -n keda

NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
keda    keda            1               2021-09-16 11:55:03.0501125 +0530 IST   deployed        keda-2.4.0      2.4.0

```

The scaled job was deployed through the following manifest definition,

```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
 name: test-keda-scaledjob
 namespace: keda-python-sample
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 120
    backoffLimit: 6 
    template:
      metadata:
        labels:
          app: order-processor-mi
          aadpodidbinding: sb-app
      spec:
       containers:
       - name: order-processor-mi
         image: <acr_name>/pysbmidemo:1.1.4
         env:
         - name: QUEUE_NAME
           value: "<receive_queue>"
         - name: QUEUE_NAME_REC
           value: "<send_queue>"
         - name: MY_POD_NAME
           valueFrom:
             fieldRef:
               fieldPath: metadata.name
  pollingInterval: 1
  successfulJobsHistoryLimit: 2    
  failedJobsHistoryLimit: 50                 
  # envSourceContainerName: {container-name} 
  maxReplicaCount: 100                        
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: "<receive_queue>"
      namespace: "<service_bus_namespace>"
      messageCount: "1"
    authenticationRef:
      name: azure-servicebus-auth
```
