### ISSUE TITLE
Support the namespace as a value parameter

### ISSUE THREAD

**Issue by justinmchase** [kedacore/charts#196]
I am using keda as a dependency of my main chart and helm does not support specifying namespaces for dependencies. As a result keda is installing into the wrong namespace.

### Use-Case
```yaml
# ./example/Chart.yaml
dependencies:
- name: keda
  version: "2.4.0"
  repository: https://kedacore.github.io/charts
```

```sh
helm install example ./example --namespace example 
```

### Specification

- [ ] Keda still installs into the "keda" namespace
- [ ] I can optionall specify a different namespace for keda to install to

### Additional Info
To provide a value, such as a namespace, to a dependency I believe that your values.yaml file should define a field called `namespace: keda`.

Then throughout the resources in your chart you would use:
```yaml
metadata:
  namespace: {{ .Values.namespace }}
```

Then it would always go to the keda namespace and if I wanted it to go to a different namespace then I would run:

```sh
helm install example ./example --set keda.namesapce=whatever
```
