### ISSUE TITLE
Chart should not set Azure Workload TenantId annotation when blank

### ISSUE THREAD

**Issue by pinkfloydx33** [kedacore/charts#284]
When using Azure Workload Identity, the chart creates a Service Account with the following labels and annotations:

```yaml
metadata:
  labels:
    azure.workload.identity/use:  "true"
  annotations:
    azure.workload.identity/client-id: "client-id"
    azure.workload.identity/tenant-id: "tenant-id"
    azure.workload.identity/service-account-token-expiration: 3600
```

The problem is that Tenant Id is **not a required annotation**. When unspecified, the default tenant Id as associated with the AZWI installation is used. In other terms, when **absent** the Azure Workload Identity web-hook will add an environment variable to the pod called `AZURE_TENANT_ID` using the value configured in the Azure Workload controller itself.

When installing KEDA via the helm chart and specifying these options, (note the absence of `podIdentity.azureWorkload.tenantId`):
```yaml
podIdentity:
  azureWorkload:
     enabled: true
     clientId: "some-id"
```

The chart creates a service account with the following metadata:

```yaml
metadata:
  labels:
    azure.workload.identity/use:  "true"
  annotations:
    azure.workload.identity/client-id: "some-id"
    azure.workload.identity/tenant-id: ""
    azure.workload.identity/service-account-token-expiration: 3600
```

The presence of the `azure.workload.identity/tenant-id` with a *blank* value then results in a pod created with the following environment variable (set by the AZWI web-hook):

```yaml
env:
- name: AZURE_TENANT_ID
```

Rather then the expected, default Tenant ID that gets created *without* the annotation:

```yaml
env:
- name: AZURE_TENANT_ID
  value: "some-default-value"
```

This will in turn cause the AZWI component to read in a blank value on [line 49 here](https://github.com/kedacore/keda/blob/f8f3cdb25031a89e423a4f07931e09f758d01c12/pkg/scalers/azure/azure_aad_workload_identity.go#L49). The request for the token will then fail.

## Expected Behavior

The chart does not add the `azure.workload.identity/tenant-id` annotation when `podIdentity.azureWorkload.tenantId` is blank/null, allowing me to omit the annotation and leverage the default value configured in AZWI, as designed.

## Actual Behavior

The chart adds the blank `azure.workload.identity/tenant-id` annotation resulting in a blank environment variable.

## Steps to Reproduce the Problem

  1. Install chart without specifying a `tenantId` in the Azure Workload options

## Specifications

  - **KEDA Version:** 2.7.1
  - **Platform & Version:** AKS 
  - **Kubernetes Version:** 1.23.5
  - **Scaler(s):** N/A

## Notes

Technically speaking, the **only** metadata that is absolutely required is the `use` label. Client Id isn't even a required annotation; the value specified on the service account (and thus via the injected `AZURE_CLIENT_ID` environment variable) is simply the *default* value. To support 1 (SA) to many (Identity) mappings, the value may be overridden in code which is exactly what Keda does when configured with the new `podIdentity.identityId` setting on `TriggerAuthentication`. 

In this case however, the AZWI web-hook does not inject a default value for Client Id, so specifying a blank value and omitting it entirely have the same net effect (an environment variable without a value). That said, for consistency's sake it might be worth omitting Client Id from the annotations when blank as well.
