### ISSUE TITLE
can you provide prometheus alert rules?

### ISSUE THREAD

**Issue by xgengsjc2021** [kedacore/charts#297]
I found there is zero rules in the values. yaml. Can you provide some rules for promtheus monitoring purpose?
Can you provide more rules? Is this one enough?
```
# - alert: KedaScalerErrors
        #   annotations:
        #     description: Keda scaledObject {{ $labels.scaledObject }} is experiencing errors with {{ $labels.scaler }} scaler
        #     summary: Keda Scaler {{ $labels.scaler }} Errors
        #   expr: sum by ( scaledObject , scaler) (rate(keda_metrics_adapter_scaler_errors[2m]))  > 0
        #   for: 2m
        #   labels:
```

**Comment by tomkerkhove** [comment]
We don't actively add them given this is up to the end-user; we don't want to enforce things on end-users.

However, if you have suggestions we do welcome PRs where we can add them, but commented out.

**Comment by xgengsjc2021** [comment]
@tomkerkhove
Where can I see all of metrics KEDA provided? I could not find any metrics on keda website, so I dont know what metrics I can use to setup alerts.

**Comment by tomkerkhove** [comment]
The overview is available on https://keda.sh/docs/2.7/operate/prometheus/

**Comment by xgengsjc2021** [comment]
@tomkerkhove Thanks. 
When I check "http://127.0.0.1:9022/metrics", I only get one metric. (However, in the document, they list 4 metrics. ) Please see my screenshot.
![Screenshot2022_08_03_133444](https://user-images.githubusercontent.com/79334945/182708234-1946daa2-f440-46ec-bae8-f58f031826bc.jpg)

From the screenshot, you can see the metric name is: **keda_metrics_adapter_scaler_errors_total** (In the document, the metric name is **keda_metrics_adapter_scaler_error_totals**) From my metric, I can get result, but if I queried **keda_metrics_adapter_scaler_error_totals**, I get nothing. Btw, I am using the latest version of KEDA(2.7.2).

Besides this, I also tried to query these other metrics below on Prometheus, but did not get any result. 
```
keda_metrics_adapter_scaled_object_error_totals
keda_metrics_adapter_scaler_errors
keda_metrics_adapter_scaler_metrics_value
```

My KEDA setting for Prometheus
```

prometheus:
    metricServer:
      enabled: true
      port: 9022
      portName: metrics
      path: /metrics
      podMonitor:
        # Enables PodMonitor creation for the Prometheus Operator
        enabled: true
        interval:
        scrapeTimeout:
        namespace: monitoring
        additionalLabels: 
          release: kube-prometheus-stack
        relabelings: []
    operator:
      enabled: true
      port: 8080
      path: /metrics
      podMonitor:
        # Enables PodMonitor creation for the Prometheus Operator
        enabled: true
        interval:
        scrapeTimeout:
        namespace: monitoring
        additionalLabels: 
          release: kube-prometheus-stack
```

Is there anything I need to modify my KEDA setting? Please help check.
