### ISSUE TITLE
metricServer can set readOnlyRootFilesystem=true

### ISSUE THREAD

**Issue by joebowbeer** [kedacore/charts#301]
The keda [README](https://github.com/kedacore/charts/tree/main/keda) in this repo states that metricServer _cannot_ set readOnlyRootFilesystem=true

> Metrics server needs to write the self-signed cert so it's not possible set this
> readOnlyRootFilesystem: true

but the [FAQ](https://keda.sh/docs/2.8/faq/) says otherwise and provides instructions how to do it when using the default generated cert:

_Originally posted by @joebowbeer in https://github.com/kedacore/charts/pull/267#discussion_r943861229_

```yaml
    readOnlyRootFilesystem: true
  volumes:
    metricsApiServer:
      extraVolumes:
      - name: keda-volume
      extraVolumeMounts:
      - name: keda-volume
        mountPath: /apiserver.local.config/certificates/
```

Please add this secure snippet to the secure-by-default values, or add a reference to the FAQ in the comment.
