### ISSUE TITLE
Helm repo index.yaml is broken.

### ISSUE THREAD

**Issue by errm** [kedacore/charts#304]
Helm repo index.yaml is somehow broken.

We are installing keda via a flux HelmRepository resource, when flux tries to update the repo it fails with this error

> failed to load Helm repository from cache: error converting YAML to JSON: yaml: line 892: did not find expected key

## Expected Behavior

That the helm repo index can be loaded by flux

## Actual Behavior

It's broken

## Steps to Reproduce the Problem

  1. Install flux
  2. Create a HelmRepository
 
 
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keda
  namespace: keda
spec:
  interval: 10m
  timeout: 60s
  url: https://kedacore.github.io/charts
```

## Specifications

  - **KEDA Version:** n/a
  - **Platform & Version:** eks / flux
  - **Kubernetes Version:** 1.22
  - **Scaler(s):** n/a
