### ISSUE TITLE
Removal of Default Resource Values in Helm Chart

### ISSUE THREAD

**Issue by JuanPabloSGU** [kedacore/charts#333]
### Proposal

This feature is about removing the default resources values in the helm chart. The solution would just commenting the default values and allow certain users to implement them if need be. 

### Use-Case

Unfortunately there has been a long standing bug [helm/helm#9027](https://github.com/helm/helm/issues/9027) that prevents default values used in dependencies to be removed (which is a common use case for argocd). 

I understand that this is not the chart behalf, but an alternative is to at least remove the cpu limit since more often then not cpu limits are considered more detrimental than anything nowadays.

**Comment by JorTurFer** [comment]
Hi @JuanPabloSGU ,
I transfer this issue to chart repository because it's more appropriate here.
I get your point and it's true what you said about CPU limit, but if the CPU limit is your issue, why don't you just define the values with a huge limit? I mean, you could define the values like:
```
resources:
  operator:
    limits:
      cpu: 10
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  metricServer:
    limits:
      cpu: 10
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
```

And this is practically removing the limit.
WDYT?
