### ISSUE TITLE
KEDA chart for 2.9.0 is broken when `podAnnotations` are provided

### ISSUE THREAD

**Issue by zerodayyy** [kedacore/charts#345]
When providing `podAnnotations.keda` in Helm values, Helm fails with an error `Error: YAML parse error on keda/templates/12-keda-deployment.yaml: error converting YAML to JSON: yaml: line 37: did not find expected key`.

After digging into Helm chart code, it's evident that when `.Values.podAnnotations.keda` is not empty AND `.Values.additionalAnnotations` is empty, invalid YAML will be produced by [this snippet](https://github.com/kedacore/charts/blob/f950fd25ee8a3d101fe13e69bc2f9f48b9c764f6/keda/templates/12-keda-deployment.yaml#L39) in 12-keda-deployment.yaml:

```yaml
      {{- if .Values.podAnnotations.keda }}
      annotations:
      {{- toYaml .Values.podAnnotations.keda | nindent 8 }}
      {{- toYaml .Values.additionalAnnotations | nindent 8 }}
      {{- end }}
```

Since those values are not linked in any way, the presence of each should be checked separately.

Similar issue is present in 22-metrics-deployment.yaml:

```yaml
      annotations:
      {{- toYaml .Values.additionalAnnotations | nindent 8 }}
      {{- if and .Values.prometheus.metricServer.enabled ( not .Values.prometheus.metricServer.podMonitor.enabled ) }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.prometheus.metricServer.port | quote }}
        prometheus.io/path: {{ .Values.prometheus.metricServer.path }}
      {{- end }}
      {{- if .Values.podAnnotations.metricsAdapter }}
      {{- toYaml .Values.podAnnotations.metricsAdapter | nindent 8}}
      {{- end }}
```

Here `.Values.additionalAnnotations` is not checked for being non-null which caused invalid YAML to be rendered:

```yaml
      annotations:
        {}  # <---- This is the rendered value of {{- toYaml .Values.additionalAnnotations | nindent 8 }}
        co.elastic.logs/enabled: "true"
```

## Expected Behavior

Rendered YAML is:

```yaml
      annotations:
        co.elastic.logs/enabled: "true"
```

## Actual Behavior

Rendered YAML is:

```yaml
      annotations:
        {}
        co.elastic.logs/enabled: "true"
```

Which causes Helm to fail

## Steps to Reproduce the Problem

  1. Provide podAnnotations.keda in values.yaml:

```yaml
podAnnotations:
  keda:
    co.elastic.logs/enabled: "true"
```
  2. Install Helm chart
  3. Helm fails with YAML parse error

## Specifications

  - **KEDA Version:** *2.9.0*
  - **Helm Chart Version:** *2.9.0*
