### ISSUE TITLE
keda http-add-on CRD not being installed.

### ISSUE THREAD

**Issue by LarsBingBong** [kedacore/charts#387]
When installing the Keda HTTP-Add-On. The latest release. The `httpscaledobjects.http.keda.sh` CRD is not installed. I've seen this a couple of times now.

## Expected Behavior

CRD is installed

## Actual Behavior

It's not

## Steps to Reproduce the Problem

  1. run `helm upgrade` on the Keda http-add-on

## Specifications

  - **KEDA Version:** v2.7.2 and Keda HTTP-add-on v0.4.1
  - **Kubernetes Version:** K3s v1.25.5+k3s1

---

  - **Scaler(s):** *Please elaborate* 

Example HTTPScaledObject
 
```yaml
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: test-web-app-dev1-pr-5351
    namespace: test-web-app-dev
spec:
    host: 5351.dev1.test-web-app.dev.heaven.com
    targetPendingRequests: 100
    scaleTargetRef:
        deployment: test-web-app-dev1-pr-5351
        service: test-web-app-dev1-pr-5351
        port: 3000
    replicas:
        min: 0
        max: 3
```

---

Other. I'm using the default values.yaml file. So CRD's is => install true

---

Thank you

**Comment by liangyuanpeng** [comment]
@LarsBingBong 

Have not get the steps for reproduce, Could you provide more detail for it?


My test:

1. helm install keda kedacore/keda
2. helm install keda-http kedacore/keda-add-ons-http
3. kubectl apply test.yaml

test.yaml:
```yaml
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: test-web-app-dev1-pr-5351
spec:
    host: 5351.dev1.test-web-app.dev.heaven.com
    targetPendingRequests: 100
    scaleTargetRef:
        deployment: test-web-app-dev1-pr-5351
        service: test-web-app-dev1-pr-5351
        port: 3000
    replicas:
        min: 0
        max: 3
```

And the httpscaledobject was created.
