### ISSUE TITLE
Remove default container resources

### ISSUE THREAD

**Issue by jgutschon** [kedacore/charts#413]
The default container resources [here](https://github.com/kedacore/charts/blob/main/keda/values.yaml#L275) should be removed to allow these fields to be overridden and removed when deploying KEDA as a subchart.

### Use-Case

When deploying KEDA as a subchart, the default resources cannot be overridden using extra YAML configuration. For example, when running KEDA as a dependent chart with the following configuration:

```yaml
keda:
  resources:
    operator:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
```

the following live manifest is produced:

```yaml
keda:
  resources:
    operator:
      limits:
        cpu: 1
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
```

The `cpu: null` field was not used and the default value persists. 

There are some issues open to address the underlying Helm issue that is causing this such as https://github.com/helm/helm/issues/9027, but for now, I think the best solution would be to comment out the default resources and allow the user to specify these.
