### ISSUE TITLE
Wrong indentation for extraVolumes and extraVolumeMounts in 14-keda-deployment.yaml

### ISSUE THREAD

**Issue by iggyshu** [kedacore/charts#415]
Similar to #411 , the indentation is incorrect in 14-keda-deployment.yaml, lines [145](https://github.com/kedacore/charts/blob/da34dd6faa5237371afe54ab03faa87f250d720f/keda/templates/14-keda-deployment.yaml#L145) and [170](https://github.com/kedacore/charts/blob/da34dd6faa5237371afe54ab03faa87f250d720f/keda/templates/14-keda-deployment.yaml#L170)

## Expected Behavior
It should be possible to provide additional `extraVolumes` and `extraVolumeMounts`.

## Actual Behavior
The chart fails to deploy when `extraVolumes` and/or `extraVolumeMounts` are supplied.

## Steps to Reproduce the Problem

  1. Deploy the helm chart with example values:

```yaml
volumes:
  keda:
    extraVolumeMounts:
    - mountPath: /etc/ssl/certs/somecert.pem
      name: some-cm
      subPath: some-path
    extraVolumes:
    - configMap:
        name: another-cm
      name: test
```

```bash
helm install keda kedacore/keda --namespace keda --values example-values.yml --debug
```

  2. Produces an error:
  
```
Error: INSTALLATION FAILED: YAML parse error on keda/templates/14-keda-deployment.yaml: error converting YAML to JSON: yaml: line 100: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 100: did not find expected key
YAML parse error on keda/templates/14-keda-deployment.yaml
```

3. Reducing nindent to 10 and 6 on lines 145 and 170 fixes the problem.

## Specifications

  - **KEDA Version:** 2.10.1
  - **Platform & Version:** NA
  - **Kubernetes Version:** 1.26.2
  - **Scaler(s):** NA
