### ISSUE TITLE
Provide a way to configure Deployment labels/annotations per component

### ISSUE THREAD

**Issue by nonoswz** [kedacore/charts#418]
I would like to be able to provide labels and annotations at the `Deployment` level, similarly to what is done for pods through the following values

````
podAnnotations:
  keda: {}
  metricsAdapter: {}
  webhooks: {}
podLabels:
  keda: {}
  metricsAdapter: {}
  webhooks: {}
````
Currently, the only possibility to configure labels and annotations for the Deployment are through`additionalLabels` and `additionalAnnotations` which are common to most Kubernetes objects deployed by Keda and are not specific per component (operator, metrics-apiserver, webhooks). I would like them to be configurable per component so they could have different values.  

### Use-Case

I would need that to properly configure Datadog annotations on every Keda Deployment, see [Datadog documentation](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes#full-configuration) where service should be either 'operator', 'metrics-apiserver' or 'webhook' and not 'keda'.

### Specification
I'd like to get a similar interface as provided for pods, so it could look like the following:

````
deploymentAnnotations:
  keda: {}
  metricsAdapter: {}
  webhooks: {}
deploymentLabels:
  keda: {}
  metricsAdapter: {}
  webhooks: {}
````

and those would be used respectively in each Deployment, example for metrics-apiserver [here](https://github.com/kedacore/charts/blob/main/keda/templates/22-metrics-deployment.yaml#L6) for annotations and [here](https://github.com/kedacore/charts/blob/main/keda/templates/22-metrics-deployment.yaml#L8) for labels.

Thanks!

**Comment by tomkerkhove** [comment]
@kedacore/keda-maintainers We are in a mixed state where we have this:

```
podAnnotations:
  keda: {}
  metricsAdapter: {}
  webhooks: {}
podLabels:
  keda: {}
  metricsAdapter: {}
  webhooks: {}
```

But also others that start with `{component}.foo.bar`.

I personally think the latter is the way forward but I'm curious about your your thoughts?

I like this proposal btw! Are you willing to contribute this once we agree on approach, @nonoswz?
