### ISSUE TITLE
Prometheus Keda Metrics have no Keda metrics

### ISSUE THREAD

**Issue by tintranvan** [kedacore/charts#425]
## Expected Behavior

Prometheus Exporter Metrics can be show metrics like here

https://keda.sh/docs/2.10/operate/prometheus/

## Actual Behavior

I have run helm chart below 

```
 prometheus:
  metricServer:
    enabled: true
    port: 9022
    portName: metrics
    path: /metrics
    podMonitor:
      # Enables PodMonitor creation for the Prometheus Operator
      enabled: false
      interval:
      scrapeTimeout:
      namespace: monitoring
      additionalLabels: {}
      relabelings: []
  operator:
    enabled: true
    port: 8080
    podMonitor:
      # Enables PodMonitor creation for the Prometheus Operator
      enabled: false
      interval:
      scrapeTimeout:
      namespace: monitoring
      additionalLabels: {}
      relabelings: []

```

But when i was checking metrics URL from : server:8080/metrics and server:9022/metrics, it not show expectation metrics

For Metrics Server server:9022/metrics showed

```
# HELP keda_metrics_adapter_scaler_errors_total Total number of errors for all scalers
# TYPE keda_metrics_adapter_scaler_errors_total counter
keda_metrics_adapter_scaler_errors_total 0

```

For Operator server:9022/metrics showed

```
# HELP certwatcher_read_certificate_errors_total Total number of certificate read errors
# TYPE certwatcher_read_certificate_errors_total counter
certwatcher_read_certificate_errors_total 0
# HELP certwatcher_read_certificate_total Total number of certificate reads
# TYPE certwatcher_read_certificate_total counter
certwatcher_read_certificate_total 0
# HELP controller_runtime_active_workers Number of currently used workers per controller
# TYPE controller_runtime_active_workers gauge
controller_runtime_active_workers{controller="scaledobject"} 0
# HELP controller_runtime_max_concurrent_reconciles Maximum number of concurrent reconciles per controller
# TYPE controller_runtime_max_concurrent_reconciles gauge
controller_runtime_max_concurrent_reconciles{controller="scaledobject"} 1
# HELP controller_runtime_reconcile_errors_total Total number of reconciliation errors per controller
# TYPE controller_runtime_reconcile_errors_total counter
controller_runtime_reconcile_errors_total{controller="scaledobject"} 0
# HELP controller_runtime_reconcile_time_seconds Length of time per reconciliation per controller
# TYPE controller_runtime_reconcile_time_seconds histogram
controller_runtime_reconcile_time_seconds_bucket{controller="scaledobject",le="0.005"} 160
controller_runtime_reconcile_time_seconds_bucket{controller="scaledobject",le="0.01"} 160
controller_runtime_reconcile_time_seconds_bucket{controller="scaledobject",le="0.025"} 160
controller_runtime_reconcile_time_seconds_bucket{controller="scaledobject",le="0.05"} 160
controller_runtime_reconcile_time_seconds_bucket{controller="scaledobject",le="0.1"} 160
controller_runtime_reconcile_time_seconds_bucket{controller="scaledobject",le="0.15"} 160
controller_runtime_reconcile_time_seconds_bucket{controller="scaledobject",le="0.2"} 160
controller_runtime_reconcile_time_seconds_bucket{controller="scaledobject",le="0.25"} 160
controller_runtime_reconcile_time_seconds_bucket{controller="scaledobject",le="0.3"} 160
controller_runtime_reconcile_time_seconds_bucket{controller="scaledobject",le="0.35"} 160

............
```

I didn't see anything expectaion keda metric like

```
keda_scaler_activity - This metric marks whether the particular scaler is active (value == 1) or in-active (value == 0).
keda_scaler_metrics_value - The current value for each scaler’s metric that would be used by the HPA in computing the target average.
keda_scaler_metrics_latency - The latency of retrieving current metric from each scaler.
keda_scaler_errors - The number of errors that have occurred for each scaler.
keda_scaler_errors_total - The total number of errors encountered for all scalers.
keda_scaled_object_errors - The number of errors that have occurred for each ScaledObejct.
keda_resource_totals - Total number of KEDA custom resources per namespace for each custom resource type (CRD).
keda_trigger_totals

keda_metrics_adapter_scaler_errors_total - The total number of errors encountered for all scalers.
keda_metrics_adapter_scaled_object_error_totals- The number of errors that have occurred for each scaled object.
keda_metrics_adapter_scaler_errors - The number of errors that have occurred for each scaler.
keda_metrics_adapter_scaler_metrics_value
```

## Steps to Reproduce the Problem

  1. Install KEDA by helm chart
  2. Check Keda  metrics by keda-operator-metrics-apiserver service

## Specifications

  - **KEDA Version:** *2.9.4*

  - **Kubernetes Version:** *1.23.6*
