### ISSUE TITLE
Prometheus unable to scrape operator metrics 

### ISSUE THREAD

**Issue by ZacBrumbaugh-KR** [kedacore/charts#438]
We have deployed Keda and prometheus and several other services to our cluster but are unable to see any keda metrics in prometheus. We are interested particularly in "keda_scaler_errors" and "keda_scaler_errors_total" but neither seem to be available in prometheus. 

When running curl against the metrics endpoint of the keda operator, we are able to see a list of metric events that appear to have valid data but that don't get picked up in prometheus. Other services' metric data is available in prometheus successfully, only keda seems to be not working for us.

Example:

 curl XXX.XX.XX.120:8080/metrics

returns:

```
keda_scaler_errors{metric="s0-prometheus-nginx_ingress_controller_requests",namespace="<MY_NAMESPACE>",scaledObject="<MY_SCALED_OBJECT>",scaler="prometheusScaler",scalerIndex="0"} 41846
keda_scaler_errors{metric="s0-prometheus-nginx_ingress_controller_requests",namespace="<MY_NAMESPACE>",scaledObject="<MY_SCALED_OBJECT>",scaler="prometheusScaler",scalerIndex="0"} 12
keda_scaler_errors{metric="s0-prometheus-nginx_ingress_controller_requests",namespace="<MY_NAMESPACE>",scaledObject="<MY_SCALED_OBJECT>",scaler="prometheusScaler",scalerIndex="0"} 12
# HELP keda_scaler_errors_total Total number of errors for all scalers
# TYPE keda_scaler_errors_total counter
keda_scaler_errors_total 41876
```

## Expected Behavior
Keda operator metrics that are available on :8080/metrics should be scraped by prometheus.

## Actual Behavior
Keda Metric data is not available in promethus.

## Steps to Reproduce the Problem

  1. Enable and deploy promethus metrics and annotations in Keda helm chart
  Actual configuration:

   ```
    podAnnotations:
      keda:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        prometheus.io/scheme: http
        metrics.dynatrace.com/scrape: "true"
        metrics.dynatrace.com/port: "8080"
      webhooks:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        prometheus.io/scheme: http
        metrics.dynatrace.com/scrape: "true"
        metrics.dynatrace.com/port: "8080"

TRUNCATED CONFIG

    webhooks:
      enabled: true

    prometheus:
      operator:
        enabled: true
        port: 8080
        path: /metrics
      webhooks:
        enabled: true
        port: 8080
        path: /metrics

```
  2. Check to confirm metrics have data via `curl <KEDA_OPERATOR_POD_IP>:8080/metrics`
  3. Search any keda metric in promethus and confirm data is not available.

## Specifications

  - **KEDA Version:** 2.10.1
  - **Platform & Version:** AKS
  - **Kubernetes Version:** 1.24.9

**Comment by tomkerkhove** [comment]
@JorTurFer Do you have an idea?

**Comment by ZacBrumbaugh-KR** [comment]
This was a configuration issue. PodMonitor or ServiceMonitor must be explicitly enabled like so
```
prometheus:
  operator:
    enabled: true
    port: 8001
    path: /metrics
    serviceMonitor:
      enabled: true
  webhooks:
    enabled: true
    port: 8002
    path: /metrics
    serviceMonitor:
      enabled: true
```
