### ISSUE TITLE
.tgz file contains backslashes when using keda chart as a subchart on macOS (and probably linux in general)

### ISSUE THREAD

**Issue by mboutet** [kedacore/charts#44]
`.tgz` file contains backslashes when using keda chart as a subchart on macOS (and probably linux in general).

1. To reproduce, create a chart with the following `Chart.yaml`:
```
apiVersion: v2
appVersion:  0.0.0
description: test
name: test
version: 0.0.0

dependencies:
  - name: keda
    repository: https://kedacore.github.io/charts
    version: =1.3.2
```
2. run `helm dependency update test`.  This will create the the `test/charts/keda-1.3.2.tgz` file.
3. Then, untar the file using `tar xf test/charts/keda-1.3.2.tgz -v`
4. The extracted files are not in the expected folder structure.

Output of `helm version`:
`version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`
