### ISSUE TITLE
Upgrade to Chart 2.11.0 Throws Errors

### ISSUE THREAD

**Issue by pinkfloydx33** [kedacore/charts#481]
Our Flux deployment of KEDA has attempted to automatically upgrade to the latest chart related a few minutes ago. It is failing and throwing the following message in the logs:

> Helm upgrade failed: YAML parse error on keda/templates/manager/service.yaml: error converting YAML to JSON: yaml: line 7: did not find expected key

I don't have better logs at the moment as the above is what is reported by Flux on my `HelmRelease` resources. I can try and do a manual install into the environment and see if I get a better error message, but it would need to wait until at least tomorrow.

## Expected Behavior

Chart succeeds

## Actual Behavior

Chart fails

## Steps to Reproduce the Problem

  1. Have 2.10.2 installed
  2. Upgrade to 2.11.0

Values: 
```yaml
nodeSelector:
  some/node.selector: 'true'
podIdentity:
  azureWorkload:
    clientId: ''
    enabled: true
prometheus:
  metricServer:
    enabled: true
  operator:
    enabled: true
    port: 8080
  webhooks:
    enabled: true
```

This is happening in multiple environments with similar values files.

## Specifications

  - **KEDA Version:** chart 2.10.2 -> 2.11.0
  - **Platform & Version:** AKS
  - **Kubernetes Version:** 1.25.6
