### ISSUE TITLE
Cannot Provide Both TLS CA Cert and Client Cert for KEDA Deployment

### ISSUE THREAD

**Issue by wsugarman** [kedacore/charts#503]
With the introduction of TLS support for external scalers in https://github.com/kedacore/keda/pull/4407, `ScaledObject` resources may now include both a CA certificate to validate the certificate authority used by the external scaler server as well as its own certificate. However, there appears to only be one value for passing gRPC TLS secrets in the KEDA helm chart: `grpcTLSCertsSecret`. Specifying both the CA cert and the client cert would require two secrets, volumes, and volume mounts for the `Deployment` resource.

Am I missing something? I suppose you could use the `hashiCorpVaultTLS` value as a workaround.

## Expected Behavior
The ability to pass multiple secrets, perhaps as an array like `grpcTLSCertsSecrets`? Or if that's confusing given the existing value and wanting to avoid removing it as a breaking change until v3, add a new value as the current one was historically used for the CA only, like `grpcKedaTLSCertsSecret` or something?

For example:
```yaml
grpcTLSCertsSecrets:
- name: serverCert
  secretName: kedaTlsCert
  mountPath: server
- name: caCert
  secretName: scalerTlsCaCert
  mountPath: ca
 ```

## Actual Behavior
Only 1 TLS secret may be specified today for the Helm chart that's designated for gRPC communication with external scalers.

## Specifications

  - **KEDA Version:** >= 2.11.0
  - **Scaler(s):** External Scalers
