### ISSUE TITLE
Cannot define liveness/readiness probes via helm chart

### ISSUE THREAD

**Issue by slawekww** [kedacore/charts#508]
## Expected Behavior

It should be possible to define liveness/readiness probe values, now all is hardcoded and for some systems timeout=1s is not acceptable.
Allow to define those probes at values.yaml for helm chart (at least for manager component).

## Actual Behavior

Cannot change those values via current chart:
https://github.com/kedacore/charts/blob/9fbc23667f4dd1e37f0b9c9e19dc2ff1a4dbfc45/keda/templates/manager/deployment.yaml#L94

## Steps to Reproduce the Problem

  1. use helm chart for keda

## Specifications

  - **KEDA Version:** chart version 2.11.2
  - **Platform & Version:** N/A
  - **Kubernetes Version:** N/A
  - **Scaler(s):** N/A

**Comment by JorTurFer** [comment]
Are you willing to adding support for it?

**Comment by slawekww** [comment]
If it is not urgent, I may try to implement as it is defined in bitnami template:
https://github.com/bitnami/charts/blob/main/template/CHART_NAME/values.yaml

I may have time within the month as it is not urgent.

**Comment by JorTurFer** [comment]
It's not urgent at all. We plan to cut a release at the end of the month, but helm chart can be released also before or after as it has it's own release cycle (basically, on demand xD)

**Comment by dttung2905** [comment]
Hi @slawekww , I'm working on a PR. May I know exactly which value you want to parameterise ?

**Comment by slawekww** [comment]
HI @dttung2905, I plan to add values in `values.yaml`:

```yaml
operator:
  # Liveness probes
    livenessProbe:
      initialDelaySeconds:  25
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
  # Readiness probes
    readinessProbe:
      initialDelaySeconds: 20
      periodSeconds: 3
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
```

and use them in [charts/keda/templates/manager/deployment.yaml](https://github.com/kedacore/charts/blob/9fbc23667f4dd1e37f0b9c9e19dc2ff1a4dbfc45/keda/templates/manager/deployment.yaml#L94)

The default would be like it is now and it allows to define values by users, especially `timeoutSeconds`.
