### ISSUE TITLE
install via helmfile doesn't install CRDs

### ISSUE THREAD

**Issue by amilkov3** [kedacore/charts#525]
adding keda as a helmfile `release` and doing `helmfile apply` doesnt install CRDS but manually doing a `helm install keda kedacore/keda --namespace keda --create-namespace` and then removing keda from the helmfile followed by a `helmfile apply` does install CRDs

i've run into similar behavior with vanilla helm3. manually adding a `crds` dir  and overriding the necessary annotations mitigates the issue but its sloppy

## Expected Behavior

installs the CRDs

## Actual Behavior

```
unable to build kubernetes objects from release manifest: resource mapping not found for name: "cron-server-scale" namespace: "keda" from "": no matches for kind "ScaledObject" in version "keda.sh/v1alpha1"
  ensure CRDs are installed first
```

## Steps to Reproduce the Problem

```
repositories:
  - name: kedacore
    url: https://kedacore.github.io/charts

releases:
  - name: keda
    namespace: keda
    chart: kedacore/keda
```

## Specifications

  - **KEDA Version:** *latest*
  - **Platform & Version:** *Please elaborate*
  - **Kubernetes Version:** *1.28*
  - **Scaler(s):** *Please elaborate*
