### ISSUE TITLE
`nano` is not a valid `timeEncoding` configuration for `operator` and `webhooks`

### ISSUE THREAD

**Issue by DaazKu** [kedacore/charts#575]
The README state that we can use `nano` as a valid time encoding for:
- `operator` -> https://github.com/kedacore/charts/blob/bb6c9af8da314cda7a4e5536c630e6069ef2ea22/keda/README.md?plain=1#L119
-  `webhook` -> https://github.com/kedacore/charts/blob/bb6c9af8da314cda7a4e5536c630e6069ef2ea22/keda/README.md?plain=1#L258 (note that it says operator. C/P issue)

Trying to do so results in the following error:
> 2023-11-27T16:32:51.521594883Z invalid argument "nano" for "--zap-time-encoding" flag: invalid time-encoding value "nano"

## Steps to Reproduce the Problem

Use the following to configure the chart:
```
logging:
  operator:
    level: error
    format: json
    timeEncoding: nano
  metricServer:
    level: 0
    stderrthreshold: ERROR
  webhooks:
    level: error
    format: json
    timeEncoding: nano
```    
    
## Specifications

  - **KEDA Version:** *2.12.0*
