### ISSUE TITLE
global.image.registry is not considered at all

### ISSUE THREAD

**Issue by 24mu13** [kedacore/charts#649]
I would expect to override the registry (e.g. ghcr.io) with a custom one, using the value global.image.registry.
Instead it will use all the default values on image.*.repository..

## Expected Behavior

Override the registry at global level.

## Actual Behavior

It uses the various default repositories.

## Steps to Reproduce the Problem

  1. `helm install keda kedacore/keda --namespace keda --create-namespace --set general.image.registry=myregistry.io`
  2. the setting is ignored!

## Possible Workaround

Simply set all the various repositories:

```yaml
image:
  keda:
    repository: myregistry.io/kedacore/keda
  metricsApiServer:
    repository: myregistry.io/kedacore/keda-metrics-apiserver
  webhooks:
    repository: myregistry.io/kedacore/keda-admission-webhooks    
```

## Specifications

  - **KEDA Version:** 2.14.0
