### ISSUE TITLE
keda admissionwebhook goes out of sync in argocd due to cabuundle field 

### ISSUE THREAD

**Issue by krimeshshah** [kedacore/charts#681]
Recently I updated keda to a helm release version 2.15.1. After two days suddenly i noticed that keda-admission webhook was out of sync  and could see that in the live manifest or the definition exists in the clusters has cabundle field under clientconfig in webhook configuration. While in desired manifest it does not have the cabundle field. As per the official k8s documentation https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/ for admission webhook cabundle is a required field hence i am little surprised why it is not there in ithe keda webhook template https://github.com/kedacore/charts/blob/main/keda/templates/webhooks/validatingconfiguration.yaml#L25. It also seems that it is not the recent changes that cabundle field not there in that case how come keda amdission webhook was generating the cabundle itself?
## Expected Behavior
kedaadmission webhook should not go out of sync

## Actual Behavior
keda admission webhook shows out of sync

## Steps to Reproduce the Problem

  1. Deploy latest keda helm release 2.15.1 
  2.  if you have argocd as a deployment tool , i see keda admission webhook out of sync
  3. Also get the output of deployed keda admissionwebhook

## Specifications

  - **KEDA Version:** *Helm release 2.15.1*
  - **Platform & Version:** *Kubernetes*
  - **Kubernetes Version:** *1,28.9*
  - **Scaler(s):** *Please elaborate*

**Comment by Evalle** [comment]
I faced the same issue with keda 2.16 and argocd.

**Comment by JordanYefet** [comment]
I'm facing the same issue deploying it using Helm.
I'm not getting this "OutOfSync" error when I deploy it directly (without helm).

**Comment by JordanYefet** [comment]
I added the following code under `spec.template.spec` :

```
- group: admissionregistration.k8s.io
  kind: ValidatingWebhookConfiguration
  name: keda-admission
  jsonPointers:
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/1/clientConfig/caBundle
    - /webhooks/2/clientConfig/caBundle
```

It seems that wildcards are not supported, and if you still want a more granular solution I'd suggest using this instead:

```
- group: admissionregistration.k8s.io
  kind: ValidatingWebhookConfiguration
  name: keda-admission
  jsonPointers:
    - /webhooks
```
