### ISSUE TITLE
structured logging for the metric server

### ISSUE THREAD

**Issue by tormodmacleod** [kedacore/charts#726]
currently the chart allows you to configure structured logging for the operator and webhooks. but there is no such option for the metric server

```
logging:
  operator:
    level: info
    format: console
    timeEncoding: rfc3339
    stackTracesEnabled: false
  metricServer:
    level: 0
    stderrthreshold: ERROR
  webhooks:
    level: info
    format: console
    timeEncoding: rfc3339
```

we ship our logs to newrelic. any logs that are in json format can be easily parsed. i'm sure most other providers like elasticsearch do the same. this allows us to easily alert on any attribute such as log level et cetera. it'd be really nice if there was a `format` key under `logging.metricServer` to allow this
