### ISSUE TITLE
Security ClusterRole - Keda Helm Chart

### ISSUE THREAD

**Issue by giandv** [kedacore/charts#750]
### Use-Case

If in our Keda configuration is not used in ScaledJob could we disable this object and related rules?

**Kubescape Security Analysis**

<img width="1172" alt="Image" src="https://github.com/user-attachments/assets/3b8c8e32-adf1-47fe-be47-04c5a2f326ae" />

Security Standard Requirement Link: https://hub.armosec.io/docs/c-0007

### Specification

What do you think if we added a nested flag in the operator object located in values.yaml?

```
operator:
   enableScaledJobs: true
```

Thanks for the support

**Comment by zroubalik** [comment]
FWIW, we would also need to update core operator (don't start a controller and bunch of other things)

**Comment by giandv** [comment]
Hi @zroubalik, thanks for your reply. 
Or could accomodate the opposite: i.e. disable ScaledJob objects, thus affecting the sections in the CRDs. 

```
operator:
   disableScaledJobs: true
```

Default value false and handle conditions like that:

**Example ClusterRole keda-operator**
```
...
{{- if .Values.operator.disableScaledJobs }}{{- else }}
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
...
```

What do you think?
